# Generated by Django 5.2.16 on 2026-08-30 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("FLEET_MANAGER", "Fleet Manager"),
                            ("DISPATCHER", "Dispatcher"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("TRANSPORT_REQUESTS", "Transport Requests"),
                            ("DISPATCH_BOARD", "Dispatch Board"),
                            ("LIVE_MAP", "Live Map"),
                            ("DRIVERS", "Drivers"),
                            ("VEHICLES", "Vehicles"),
                            ("FUEL_ANALYTICS", "Fuel Analytics"),
                            ("MAINTENANCE", "Maintenance"),
                            ("SYSTEM_SETTINGS", "System Settings"),
                            ("USERS_ACCESS", "Users & Access"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("VIEW", "View"),
                            ("EDIT", "Edit"),
                            ("APPROVE", "Approve"),
                            ("CANCEL", "Cancel"),
                            ("ASSIGN", "Assign"),
                            ("DISPATCH", "Dispatch"),
                            ("OVERRIDE", "Override"),
                            ("MANAGE_GEOFENCES", "Manage Geofences"),
                            ("CREATE", "Create"),
                            ("MANAGE_DOCUMENTS", "Manage Documents"),
                            ("CHANGE_STATUS", "Change Status"),
                            ("INSPECT", "Inspect"),
                            ("VIEW_USERS", "View Users"),
                            ("CREATE_USER", "Create User"),
                            ("EDIT_USER", "Edit User"),
                            ("CHANGE_USER_STATUS", "Change User Status"),
                            ("ASSIGN_ROLE", "Assign Role"),
                            ("MANAGE_ROLE_PERMISSIONS", "Manage Role Permissions"),
                        ],
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("role", "module", "action"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("role", "module", "action"),
                        name="accounts_unique_role_module_action",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("role__in", ["FLEET_MANAGER", "DISPATCHER"])
                        ),
                        name="accounts_rolepermission_managed_role",
                    ),
                ],
            },
        ),
    ]
