import { useEffect, useState } from "react";
import LoadingIndicator from "../../components/common/LoadingIndicator";
import { getVehicles, type Vehicle, type VehiclePage } from "../../services/vehicles";
import "./MaintenancePage.css";

const inspectionLabel = (vehicle: Vehicle) => vehicle.latest_inspection ? vehicle.latest_inspection.result.replaceAll("_", " ") : "No inspection record";

export default function MaintenancePage() {
  const [page, setPage] = useState<VehiclePage | null>(null);
  const [search, setSearch] = useState("");
  const [state, setState] = useState<"loading" | "ready" | "error">("loading");
  useEffect(() => { const controller = new AbortController(); const query = search.trim() ? `search=${encodeURIComponent(search.trim())}` : ""; getVehicles(query, controller.signal).then(result => { setPage(result); setState("ready"); }).catch(error => { if (error?.name !== "AbortError") setState("error"); }); return () => controller.abort(); }, [search]);
  if (state === "loading") return <main className="maintenance-page"><div className="maintenance-card maintenance-state"><LoadingIndicator variant="inline" message="Loading fleet maintenance records…" /></div></main>;
  if (state === "error") return <main className="maintenance-page"><div className="maintenance-card maintenance-state" role="alert"><strong>Fleet maintenance records unavailable</strong><p>Vehicle and inspection data could not be loaded.</p></div></main>;
  const vehicles = page?.results ?? [];
  return <main className="maintenance-page">
    <header className="maintenance-header"><div><p className="breadcrumb">Operations / Maintenance &amp; Predictions</p><h1>Maintenance &amp; Predictions</h1></div><span className="maintenance-badge">Predictions unavailable</span></header>
    <nav className="maintenance-tabs" role="tablist" aria-label="Maintenance views"><button type="button" role="tab" className="active" aria-selected="true">Overview</button><button type="button" role="tab" aria-selected="false" disabled>Maintenance Review</button><button type="button" role="tab" aria-selected="false" disabled>Inspection Records</button></nav>
    <section className="maintenance-grid" aria-label="Maintenance summary"><article className="maintenance-card"><small>Fleet vehicles</small><strong>{page?.count ?? 0}</strong><span>Registered records</span></article><article className="maintenance-card"><small>Needs attention</small><strong>{vehicles.filter(vehicle => vehicle.latest_inspection && vehicle.latest_inspection.result !== "PASSED").length}</strong><span>Inspection evidence only</span></article><article className="maintenance-card"><small>Inspection records</small><strong>{vehicles.filter(vehicle => vehicle.latest_inspection).length}</strong><span>Shown on this page</span></article><article className="maintenance-card"><small>Maintenance predictions</small><strong>Unavailable</strong><span>No operational source</span></article></section>
    <section className="maintenance-card maintenance-table-card"><header className="maintenance-section-header"><h2>Fleet Maintenance Overview</h2><label aria-label="Search vehicles"><input type="search" placeholder="Search vehicles" value={search} onChange={event => { setPage(null); setState("loading"); setSearch(event.target.value); }} /></label></header>{vehicles.length === 0 ? <div className="maintenance-empty"><strong>No vehicle records found</strong><p>{search ? "Try a different search." : "No registered vehicles are available for maintenance review."}</p></div> : <><div className="maintenance-table-wrap"><table><thead><tr><th>Vehicle</th><th>Plate</th><th>Status</th><th>Latest Inspection</th><th>Maintenance Prediction</th><th>Review</th></tr></thead><tbody>{vehicles.map(vehicle => { const needsReview = vehicle.latest_inspection?.result !== undefined && vehicle.latest_inspection.result !== "PASSED"; return <tr key={vehicle.device_id}><td><strong>{vehicle.display_name}</strong><small>{vehicle.device_id}</small></td><td>{vehicle.plate_number || "Not recorded"}</td><td><span className={`maintenance-status ${vehicle.is_active ? "maintenance-status--active" : "maintenance-status--inactive"}`}>{vehicle.is_active ? "Active" : "Inactive"}</span></td><td>{inspectionLabel(vehicle)}{vehicle.latest_inspection && <small>{vehicle.latest_inspection.inspection_date}</small>}</td><td><span className="maintenance-unavailable">Prediction unavailable</span><small>Live inference blocked</small></td><td><span className={needsReview ? "maintenance-review" : "maintenance-neutral"}>{needsReview ? "Review needed" : "Not evaluated"}</span></td></tr>; })}</tbody></table></div><footer className="maintenance-table-footer">Showing {vehicles.length} of {page?.count ?? vehicles.length} vehicles</footer></>}</section>
    <section className="maintenance-card maintenance-notice"><h2>Prediction availability</h2><p>Per-vehicle maintenance predictions are unavailable because no persisted operational prediction source currently exists. No scores, alerts, component failures, service dates, or maintenance history are inferred.</p></section>
  </main>;
}
