# Generated by Django 5.1.7 on 2026-09-05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transport_requests", "0007_dispatch_assignment_acceptance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "source_system",
                    models.CharField(
                        choices=[
                            ("HOTEL_MANAGEMENT_SYSTEM", "Hotel management system"),
                            (
                                "RESTAURANT_MANAGEMENT_SYSTEM",
                                "Restaurant management system",
                            ),
                        ],
                        max_length=40,
                    ),
                ),
                ("key_identifier", models.CharField(editable=False, max_length=32, unique=True)),
                ("credential_hash", models.CharField(editable=False, max_length=256)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rotated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transport_integration_client",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("name", "pk"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            source_system__in=(
                                "HOTEL_MANAGEMENT_SYSTEM",
                                "RESTAURANT_MANAGEMENT_SYSTEM",
                            )
                        ),
                        name="integration_client_trusted_source",
                    )
                ],
            },
        ),
    ]
