# Generated by Django 5.2.16 on 2026-09-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_requests', '0011_tripexpensereceipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripexpensereceipt',
            name='fuel_grade',
            field=models.CharField(blank=True, choices=[('UNLEADED_91', 'Unleaded 91'), ('PREMIUM_95', 'Premium 95'), ('PREMIUM_97', 'Premium 97'), ('REGULAR_DIESEL', 'Regular diesel'), ('PREMIUM_DIESEL', 'Premium diesel')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='tripexpensereceipt',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('GASOLINE', 'Gasoline'), ('DIESEL', 'Diesel')], default='', max_length=20),
        ),
    ]
