# Generated by Django 5.1.7 on 2026-08-26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("fleet", "0002_vehicle_registry"),
    ]

    operations = [
        migrations.CreateModel(
            name="FuelPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_timestamp", models.DateTimeField()),
                ("predicted_at", models.DateTimeField(auto_now_add=True)),
                ("estimated_fuel_lph", models.DecimalField(decimal_places=4, max_digits=10)),
                ("model_name", models.CharField(max_length=160)),
                ("model_version", models.CharField(max_length=80)),
                (
                    "source_mode",
                    models.CharField(default="explicit_validated_api", max_length=40),
                ),
                ("validated_inputs", models.JSONField()),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fuel_predictions",
                        to="fleet.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ("-input_timestamp", "-predicted_at", "-pk"),
                "indexes": [
                    models.Index(
                        fields=["vehicle", "-input_timestamp"],
                        name="fuel_pred_vehicle_time_idx",
                    ),
                    models.Index(fields=["input_timestamp"], name="fuel_pred_time_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("vehicle", "input_timestamp", "model_version"),
                        name="fuel_prediction_source_unique",
                    )
                ],
            },
        ),
    ]
