# Generated by Django 5.2.16 on 2026-08-12 02:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_dynamic_model_year_ceiling'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField()),
                ('inspection_type', models.CharField(choices=[('PRE_TRIP', 'Pre-trip'), ('POST_TRIP', 'Post-trip'), ('PERIODIC', 'Periodic')], max_length=20)),
                ('result', models.CharField(choices=[('PASSED', 'Passed'), ('NEEDS_ATTENTION', 'Needs attention'), ('FAILED', 'Failed')], max_length=20)),
                ('odometer_km', models.PositiveIntegerField(blank=True, null=True)),
                ('fuel_level_percent', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('exterior_condition', models.CharField(choices=[('OK', 'OK'), ('NEEDS_ATTENTION', 'Needs attention'), ('NOT_CHECKED', 'Not checked')], max_length=20)),
                ('interior_condition', models.CharField(choices=[('OK', 'OK'), ('NEEDS_ATTENTION', 'Needs attention'), ('NOT_CHECKED', 'Not checked')], max_length=20)),
                ('tires_condition', models.CharField(choices=[('OK', 'OK'), ('NEEDS_ATTENTION', 'Needs attention'), ('NOT_CHECKED', 'Not checked')], max_length=20)),
                ('lights_condition', models.CharField(choices=[('OK', 'OK'), ('NEEDS_ATTENTION', 'Needs attention'), ('NOT_CHECKED', 'Not checked')], max_length=20)),
                ('brakes_condition', models.CharField(choices=[('OK', 'OK'), ('NEEDS_ATTENTION', 'Needs attention'), ('NOT_CHECKED', 'Not checked')], max_length=20)),
                ('fluids_condition', models.CharField(choices=[('OK', 'OK'), ('NEEDS_ATTENTION', 'Needs attention'), ('NOT_CHECKED', 'Not checked')], max_length=20)),
                ('safety_equipment_condition', models.CharField(choices=[('OK', 'OK'), ('NEEDS_ATTENTION', 'Needs attention'), ('NOT_CHECKED', 'Not checked')], max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('issues_found', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_inspections', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='fleet.vehicle')),
            ],
            options={
                'ordering': ('-inspection_date', '-created_at', '-pk'),
                'constraints': [models.CheckConstraint(condition=models.Q(('odometer_km__isnull', True), ('odometer_km__gte', 0), _connector='OR'), name='fleet_inspection_odometer_nonnegative'), models.CheckConstraint(condition=models.Q(('fuel_level_percent__isnull', True), ('fuel_level_percent__range', (0, 100)), _connector='OR'), name='fleet_inspection_fuel_range')],
            },
        ),
    ]
