# Generated by Django 5.2.16 on 2026-08-12 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_vehicleinspection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('OFFICIAL_RECEIPT', 'Official receipt'), ('CERTIFICATE_OF_REGISTRATION', 'Certificate of registration'), ('INSURANCE', 'Insurance'), ('PURCHASE_ORDER', 'Purchase order'), ('SALES_INVOICE', 'Sales invoice'), ('WARRANTY', 'Warranty'), ('LEASE_AGREEMENT', 'Lease agreement'), ('OTHER', 'Other')], max_length=40)),
                ('title', models.CharField(max_length=160)),
                ('reference_number', models.CharField(blank=True, default='', max_length=100)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('file', models.FileField(upload_to='vehicle_documents/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='acquisition_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='chassis_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('GASOLINE', 'Gasoline'), ('DIESEL', 'Diesel'), ('HYBRID', 'Hybrid'), ('ELECTRIC', 'Electric'), ('OTHER', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='ownership_type',
            field=models.CharField(blank=True, choices=[('COMPANY_OWNED', 'Company owned'), ('LEASED', 'Leased'), ('RENTED', 'Rented'), ('OTHER', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='purchase_currency',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='purchase_order_number',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registration_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='supplier_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='transmission_type',
            field=models.CharField(blank=True, choices=[('MANUAL', 'Manual'), ('AUTOMATIC', 'Automatic'), ('CVT', 'CVT'), ('OTHER', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='warranty_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_price__isnull', True), ('purchase_price__gte', 0), _connector='OR'), name='fleet_vehicle_purchase_price_nonnegative'),
        ),
        migrations.AddField(
            model_name='vehicledocument',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicledocument',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='fleet.vehicle'),
        ),
    ]
