# Generated by Django 5.2.16 on 2026-08-12 11:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_vehicledocument_vehicle_acquisition_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='gvwr_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='payload_capacity_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='vehicledocument',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicledocument',
            name='issuer_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='vehicledocument',
            name='document_type',
            field=models.CharField(choices=[('OFFICIAL_RECEIPT', 'Official receipt'), ('CERTIFICATE_OF_REGISTRATION', 'Certificate of registration'), ('INSURANCE', 'Insurance'), ('PURCHASE_ORDER', 'Purchase order'), ('SALES_INVOICE', 'Sales invoice'), ('WARRANTY', 'Warranty'), ('LEASE_AGREEMENT', 'Lease agreement'), ('EMISSION_CERTIFICATE', 'Emission certificate'), ('PMVIC_CERTIFICATE', 'PMVIC certificate'), ('VEHICLE_PHOTO', 'Vehicle photo'), ('OTHER', 'Other')], max_length=40),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.CheckConstraint(condition=models.Q(('payload_capacity_kg__isnull', True), ('payload_capacity_kg__gte', 0), _connector='OR'), name='fleet_vehicle_payload_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.CheckConstraint(condition=models.Q(('gvwr_kg__isnull', True), ('gvwr_kg__gte', 0), _connector='OR'), name='fleet_vehicle_gvwr_nonnegative'),
        ),
    ]
