# Generated by Django 5.2.16 on 2026-09-05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fleet", "0007_driver_driverdocument"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleMaintenanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("MANUAL", "Manual"), ("INSPECTION", "Inspection")],
                        default="MANUAL",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("SCHEDULED", "Scheduled"),
                            ("IN_PROGRESS", "In progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("notes", models.TextField(blank=True, default="")),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vehicle_maintenance_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inspection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenance_records",
                        to="fleet.vehicleinspection",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenance_records",
                        to="fleet.vehicle",
                    ),
                ),
            ],
            options={"ordering": ("-created_at", "-pk")},
        ),
        migrations.AddIndex(
            model_name="vehiclemaintenancerecord",
            index=models.Index(
                fields=["vehicle", "status"], name="fleet_maint_vehicle_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="vehiclemaintenancerecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("status", "SCHEDULED"), _negated=True)
                | models.Q(("scheduled_at__isnull", False)),
                name="fleet_maint_scheduled_at_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="vehiclemaintenancerecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("inspection__isnull", True), ("source", "MANUAL")),
                    models.Q(("inspection__isnull", False), ("source", "INSPECTION")),
                    _connector="OR",
                ),
                name="fleet_maint_source_matches_inspection",
            ),
        ),
    ]
