# Generated by Django 5.2.16 on 2026-09-08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("fleet", "0008_vehiclemaintenancerecord")]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="photo",
            field=models.FileField(
                blank=True, null=True, upload_to="vehicle_photos/%Y/%m/"
            ),
        ),
    ]
