# Generated by Django 5.2.16 on 2026-09-23 19:31

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("fleet", "0012_driver_safety_demo")]

    operations = [
        migrations.CreateModel(
            name="FuelPriceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[("DIESEL", "Diesel"), ("GASOLINE", "Gasoline")],
                        max_length=20,
                    ),
                ),
                (
                    "price_per_liter",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("PHP", "Philippine peso")],
                        default="PHP",
                        max_length=3,
                    ),
                ),
                ("effective_at", models.DateTimeField()),
                ("retrieved_at", models.DateTimeField(auto_now_add=True)),
                ("provider", models.CharField(max_length=160)),
                (
                    "source_mode",
                    models.CharField(
                        choices=[
                            ("EXTERNAL_CACHED", "External cached"),
                            ("MANUAL", "Manual"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("-effective_at", "-retrieved_at", "-pk"),
                "indexes": [
                    models.Index(
                        condition=models.Q(("is_active", True)),
                        fields=[
                            "fuel_type",
                            "source_mode",
                            "-effective_at",
                            "-retrieved_at",
                            "-id",
                        ],
                        name="fuel_price_active_lookup_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("fuel_type__in", ("DIESEL", "GASOLINE"))
                        ),
                        name="fuel_price_supported_type",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("currency", "PHP")),
                        name="fuel_price_php_currency",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("source_mode__in", ("EXTERNAL_CACHED", "MANUAL"))
                        ),
                        name="fuel_price_source_mode",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("price_per_liter__gt", 0)),
                        name="fuel_price_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("provider", ""), _negated=True),
                        name="fuel_price_provider_present",
                    ),
                ],
            },
        )
    ]
