# Generated by Django 5.2.16 on 2026-09-24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("fleet", "0013_fuelpricerecord")]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="fuel_type",
            field=models.CharField(
                blank=True,
                choices=[("GASOLINE", "Gasoline"), ("DIESEL", "Diesel")],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="fuel_grade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("UNLEADED_91", "Unleaded 91"),
                    ("PREMIUM_95", "Premium 95"),
                    ("PREMIUM_97", "Premium 97"),
                    ("REGULAR_DIESEL", "Regular diesel"),
                    ("PREMIUM_DIESEL", "Premium diesel"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
