# Generated by Django 5.2.16 on 2026-09-24

from django.db import migrations, models


GASWATCH_REGULAR_DIESEL_PROVIDER = "GasWatchPH [Metro Manila; reference=DIESEL]"


def classify_explicit_product_provenance(apps, schema_editor):
    FuelPriceRecord = apps.get_model("fleet", "FuelPriceRecord")
    FuelPriceRecord.objects.filter(
        provider=GASWATCH_REGULAR_DIESEL_PROVIDER,
        fuel_type="DIESEL",
    ).update(fuel_grade="REGULAR_DIESEL")


def restore_generic_product_classification(apps, schema_editor):
    FuelPriceRecord = apps.get_model("fleet", "FuelPriceRecord")
    FuelPriceRecord.objects.filter(
        provider=GASWATCH_REGULAR_DIESEL_PROVIDER,
        fuel_type="DIESEL",
        fuel_grade="REGULAR_DIESEL",
    ).update(fuel_grade="")


class Migration(migrations.Migration):
    dependencies = [("fleet", "0014_vehicle_fuel_grade")]

    operations = [
        migrations.AddField(
            model_name="fuelpricerecord",
            name="fuel_grade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("UNLEADED_91", "Unleaded 91"),
                    ("PREMIUM_95", "Premium 95"),
                    ("PREMIUM_97", "Premium 97"),
                    ("REGULAR_DIESEL", "Regular diesel"),
                    ("PREMIUM_DIESEL", "Premium diesel"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.RunPython(
            classify_explicit_product_provenance,
            restore_generic_product_classification,
        ),
    ]
