import { fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import { beforeEach, expect, test, vi } from "vitest";
import App from "../../App";

const auth=vi.hoisted(()=>({user:{id:1,username:"dispatch",display_name:"Dispatcher",role:"DISPATCHER"},loading:false,signIn:vi.fn(),signOut:vi.fn(),expire:vi.fn()}));
vi.mock("../../contexts/AuthContext",()=>({useAuth:()=>auth}));
const driver={id:1,driver_code:"DRV-001",external_hr_id:null,first_name:"Juan",middle_name:"",last_name:"Dela Cruz",full_name:"Juan Dela Cruz",contact_number:"0917",email:"juan@example.test",photo_url:null,employment_status:"ACTIVE",date_hired:null,linked_user:null,linked_user_display:null,license_number:"N01",license_category:"",license_codes:"",license_issue_date:null,license_expiry_date:"2027-08-13",medical_certificate_expiry_date:"2027-08-13",eligibility_status:"ELIGIBLE",eligibility_reasons:[],safety_score:null,safety_score_status:"NOT_SCORED",created_at:"2026-08-13T00:00:00Z",updated_at:"2026-08-13T00:00:00Z"};
const json=(value:unknown,status=200)=>Promise.resolve(new Response(JSON.stringify(value),{status,headers:{"Content-Type":"application/json"}}));
const renderPage=()=>render(<MemoryRouter initialEntries={["/drivers"]}><App/></MemoryRouter>);
beforeEach(()=>{auth.user={id:1,username:"dispatch",display_name:"Dispatcher",role:"DISPATCHER"};vi.restoreAllMocks()});

test("renders real driver split view and honest safety/eligibility details",async()=>{
 vi.spyOn(globalThis,"fetch").mockImplementation(input=>String(input).includes("documents")?json({count:0,next:null,previous:null,results:[]}):json({count:1,next:null,previous:null,results:[driver]}));renderPage();
 expect((await screen.findAllByText("Juan Dela Cruz")).length).toBeGreaterThan(1);expect(screen.queryByText("Planned module")).not.toBeInTheDocument();expect(screen.queryByText("+ Add Driver")).not.toBeInTheDocument();
 fireEvent.click(screen.getByRole("tab",{name:"Safety"}));const panel=screen.getByText("Safety scoring will become available when validated driving-behavior and incident inputs are integrated.").parentElement!;expect(panel).toHaveTextContent("—");expect(panel).toHaveTextContent("Not yet scored");expect(panel.textContent).not.toMatch(/\b\d{1,3}\s*\/\s*100\b/);
 fireEvent.click(screen.getByRole("tab",{name:"Eligibility"}));expect(screen.getByText("Safety Score is not currently used for eligibility.")).toBeInTheDocument();
 fireEvent.click(screen.getByRole("tab",{name:"Overview"}));expect(screen.getAllByText("Not linked")).toHaveLength(2);
});
test("supports empty state, search and filters",async()=>{const fetchMock=vi.spyOn(globalThis,"fetch").mockImplementation(()=>json({count:0,next:null,previous:null,results:[]}));renderPage();expect(await screen.findByText("No driver records available.")).toBeInTheDocument();fireEvent.change(screen.getByLabelText("Search drivers"),{target:{value:"Juan"}});fireEvent.change(screen.getByLabelText("Employment"),{target:{value:"ACTIVE"}});fireEvent.change(screen.getByLabelText("Eligibility"),{target:{value:"ELIGIBLE"}});await waitFor(()=>expect(String(fetchMock.mock.calls.at(-1)?.[0])).toContain("eligibility_status=ELIGIBLE"))});
test("role controls expose manager documents and super admin creation",async()=>{vi.spyOn(globalThis,"fetch").mockImplementation(input=>String(input).includes("documents")?json({count:0,next:null,previous:null,results:[]}):json({count:1,next:null,previous:null,results:[driver]}));auth.user.role="FLEET_MANAGER";const rendered=renderPage();await screen.findAllByText("Juan Dela Cruz");expect(screen.getByText("Edit")).toBeInTheDocument();fireEvent.click(screen.getByRole("tab",{name:"Documents"}));expect(await screen.findByText("Upload Document")).toBeInTheDocument();rendered.unmount();auth.user.role="SUPER_ADMIN";renderPage();expect(await screen.findByText("+ Add Driver")).toBeInTheDocument();fireEvent.click(screen.getByText("+ Add Driver"));expect(screen.getByRole("dialog",{name:"Add Driver"})).toBeInTheDocument()});
test("selection updates the detail pane and credentials render",async()=>{const second={...driver,id:2,driver_code:"DRV-002",first_name:"Maria",last_name:"Santos",full_name:"Maria Santos",license_number:"N02"};vi.spyOn(globalThis,"fetch").mockImplementation(()=>json({count:2,next:null,previous:null,results:[driver,second]}));renderPage();await screen.findByRole("button",{name:/Maria Santos/});fireEvent.click(screen.getByRole("button",{name:/Maria Santos/}));const detail=screen.getByRole("heading",{name:"Maria Santos"}).closest("header")!;expect(within(detail).getByText("DRV-002")).toBeInTheDocument();fireEvent.click(screen.getByRole("tab",{name:"Credentials"}));expect(screen.getByText("N02")).toBeInTheDocument()});
