from django.core.management.base import BaseCommand

from fleet.models import Vehicle

PASSENGER_VEHICLES = (
    (
        "DEV-PAX-001",
        "DVP-001",
        "Guest Sedan 01",
        "SEDAN",
        "Toyota",
        "Camry",
        2023,
        "Black",
        "GASOLINE",
        "AUTOMATIC",
        5,
        "450.00",
        "2100.00",
        True,
    ),
    (
        "DEV-PAX-002",
        "DVP-002",
        "Guest Sedan 02",
        "SEDAN",
        "Honda",
        "Accord",
        2022,
        "Silver",
        "GASOLINE",
        "CVT",
        5,
        "430.00",
        "2050.00",
        True,
    ),
    (
        "DEV-PAX-003",
        "DVP-003",
        "Guest SUV 01",
        "SUV",
        "Toyota",
        "Fortuner",
        2024,
        "White",
        "DIESEL",
        "AUTOMATIC",
        7,
        "650.00",
        "2750.00",
        True,
    ),
    (
        "DEV-PAX-004",
        "DVP-004",
        "Guest SUV 02",
        "SUV",
        "Mitsubishi",
        "Montero Sport",
        2023,
        "Gray",
        "DIESEL",
        "AUTOMATIC",
        7,
        "620.00",
        "2710.00",
        True,
    ),
    (
        "DEV-PAX-005",
        "DVP-005",
        "Guest SUV 03",
        "SUV",
        "Nissan",
        "Terra",
        2022,
        "Black",
        "DIESEL",
        "AUTOMATIC",
        7,
        "630.00",
        "2760.00",
        True,
    ),
    (
        "DEV-PAX-006",
        "DVP-006",
        "Guest Van 01",
        "VAN",
        "Toyota",
        "Hiace",
        2024,
        "White",
        "DIESEL",
        "MANUAL",
        12,
        "1000.00",
        "3500.00",
        True,
    ),
    (
        "DEV-PAX-007",
        "DVP-007",
        "Guest Van 02",
        "VAN",
        "Nissan",
        "Urvan",
        2023,
        "Silver",
        "DIESEL",
        "MANUAL",
        15,
        "1100.00",
        "3510.00",
        True,
    ),
    (
        "DEV-PAX-008",
        "DVP-008",
        "Guest Van 03",
        "VAN",
        "Hyundai",
        "Staria",
        2024,
        "Gray",
        "DIESEL",
        "AUTOMATIC",
        11,
        "850.00",
        "3040.00",
        True,
    ),
    (
        "DEV-PAX-009",
        "DVP-009",
        "Guest Shuttle 01",
        "SHUTTLE_BUS",
        "Toyota",
        "Coaster",
        2022,
        "White",
        "DIESEL",
        "MANUAL",
        28,
        "1600.00",
        "5670.00",
        True,
    ),
    (
        "DEV-PAX-010",
        "DVP-010",
        "Guest Shuttle 02",
        "SHUTTLE_BUS",
        "Mitsubishi Fuso",
        "Rosa",
        2021,
        "White",
        "DIESEL",
        "MANUAL",
        25,
        "1500.00",
        "5400.00",
        False,
    ),
)

LOGISTICS_VEHICLES = (
    (
        "DEV-LOG-001",
        "DVL-001",
        "Supply Van 01",
        "VAN",
        "Toyota",
        "Hiace Cargo",
        2023,
        "White",
        "DIESEL",
        "MANUAL",
        3,
        "1200.00",
        "3500.00",
        True,
    ),
    (
        "DEV-LOG-002",
        "DVL-002",
        "Supply Van 02",
        "VAN",
        "Nissan",
        "NV350",
        2022,
        "Silver",
        "DIESEL",
        "MANUAL",
        3,
        "1250.00",
        "3510.00",
        True,
    ),
    (
        "DEV-LOG-003",
        "DVL-003",
        "Supply Van 03",
        "VAN",
        "Hyundai",
        "H-100",
        2023,
        "White",
        "DIESEL",
        "MANUAL",
        3,
        "1300.00",
        "3490.00",
        True,
    ),
    (
        "DEV-LOG-004",
        "DVL-004",
        "Supply Van 04",
        "VAN",
        "Foton",
        "Toano",
        2024,
        "White",
        "DIESEL",
        "MANUAL",
        3,
        "1450.00",
        "4200.00",
        True,
    ),
    (
        "DEV-LOG-005",
        "DVL-005",
        "Supply Truck 01",
        "SERVICE_TRUCK",
        "Isuzu",
        "N-Series",
        2023,
        "White",
        "DIESEL",
        "MANUAL",
        3,
        "2800.00",
        "6500.00",
        True,
    ),
    (
        "DEV-LOG-006",
        "DVL-006",
        "Supply Truck 02",
        "SERVICE_TRUCK",
        "Mitsubishi Fuso",
        "Canter",
        2022,
        "White",
        "DIESEL",
        "MANUAL",
        3,
        "3000.00",
        "7000.00",
        True,
    ),
    (
        "DEV-LOG-007",
        "DVL-007",
        "Supply Truck 03",
        "SERVICE_TRUCK",
        "Hino",
        "300",
        2021,
        "Blue",
        "DIESEL",
        "MANUAL",
        3,
        "3200.00",
        "7500.00",
        True,
    ),
    (
        "DEV-LOG-008",
        "DVL-008",
        "Supply Motorcycle 01",
        "MOTORCYCLE",
        "Honda",
        "TMX 125",
        2024,
        "Red",
        "GASOLINE",
        "MANUAL",
        2,
        "120.00",
        "320.00",
        True,
    ),
    (
        "DEV-LOG-009",
        "DVL-009",
        "Supply Motorcycle 02",
        "MOTORCYCLE",
        "Yamaha",
        "YTX 125",
        2023,
        "Black",
        "GASOLINE",
        "MANUAL",
        2,
        "115.00",
        "315.00",
        True,
    ),
    (
        "DEV-LOG-010",
        "DVL-010",
        "Supply Truck 04",
        "SERVICE_TRUCK",
        "Isuzu",
        "NPR",
        2020,
        "White",
        "DIESEL",
        "MANUAL",
        3,
        "3500.00",
        "8000.00",
        False,
    ),
)


class Command(BaseCommand):
    help = "Create missing deterministic Vehicle Registry development records."

    def handle(self, *args, **options):
        created_count = 0
        existing_count = 0
        for record in (*PASSENGER_VEHICLES, *LOGISTICS_VEHICLES):
            (
                device_id,
                plate_number,
                display_name,
                vehicle_type,
                manufacturer,
                model,
                model_year,
                color,
                fuel_type,
                transmission_type,
                passenger_capacity,
                payload_capacity_kg,
                gvwr_kg,
                is_active,
            ) = record
            _, created = Vehicle.objects.get_or_create(
                device_id=device_id,
                defaults={
                    "plate_number": plate_number,
                    "display_name": display_name,
                    "vehicle_type": vehicle_type,
                    "manufacturer": manufacturer,
                    "model": model,
                    "model_year": model_year,
                    "color": color,
                    "fuel_type": fuel_type,
                    "transmission_type": transmission_type,
                    "passenger_capacity": passenger_capacity,
                    "payload_capacity_kg": payload_capacity_kg,
                    "gvwr_kg": gvwr_kg,
                    "ownership_type": Vehicle.OwnershipType.COMPANY_OWNED,
                    "is_active": is_active,
                },
            )
            created_count += int(created)
            existing_count += int(not created)

        self.stdout.write(
            self.style.SUCCESS(
                f"Vehicle Registry seed complete: {created_count} created, "
                f"{existing_count} existing."
            )
        )
