from django.urls import path

from .views import (
    AuditEventListView,
    ChangePasswordView,
    CsrfView,
    ForgotPasswordView,
    LoginView,
    LogoutView,
    ManagedStaffInvitationView,
    ManagedStaffListCreateView,
    ManagedStaffRoleView,
    ManagedStaffStatusView,
    MeView,
    NotificationListView,
    NotificationMarkAllReadView,
    NotificationMarkReadView,
    NotificationUnreadCountView,
    ResetPasswordView,
    RolePermissionListView,
    RolePermissionReplaceView,
    SessionActivityView,
    StaffPasswordSetupView,
    TwoFactorConfirmView,
    TwoFactorDisableView,
    TwoFactorEnrollmentConfirmView,
    TwoFactorSetupView,
    TwoFactorStatusView,
    TwoFactorVerifyView,
)

urlpatterns = [
    path("csrf/", CsrfView.as_view(), name="auth-csrf"),
    path("login/", LoginView.as_view(), name="auth-login"),
    path("forgot-password/", ForgotPasswordView.as_view(), name="auth-forgot-password"),
    path("reset-password/", ResetPasswordView.as_view(), name="auth-reset-password"),
    path("change-password/", ChangePasswordView.as_view(), name="auth-change-password"),
    path("me/", MeView.as_view(), name="auth-me"),
    path("logout/", LogoutView.as_view(), name="auth-logout"),
    path("activity/", SessionActivityView.as_view(), name="auth-activity"),
    path("audit-logs/", AuditEventListView.as_view(), name="audit-log-list"),
    path("notifications/", NotificationListView.as_view(), name="notification-list"),
    path(
        "notifications/unread-count/",
        NotificationUnreadCountView.as_view(),
        name="notification-unread-count",
    ),
    path(
        "notifications/mark-all-read/",
        NotificationMarkAllReadView.as_view(),
        name="notification-mark-all-read",
    ),
    path(
        "notifications/<int:notification_id>/read/",
        NotificationMarkReadView.as_view(),
        name="notification-mark-read",
    ),
    path("2fa/status/", TwoFactorStatusView.as_view(), name="two-factor-status"),
    path("2fa/setup/", TwoFactorSetupView.as_view(), name="two-factor-setup"),
    path("2fa/confirm/", TwoFactorConfirmView.as_view(), name="two-factor-confirm"),
    path(
        "2fa/enrollment/confirm/",
        TwoFactorEnrollmentConfirmView.as_view(),
        name="two-factor-enrollment-confirm",
    ),
    path("2fa/verify/", TwoFactorVerifyView.as_view(), name="two-factor-verify"),
    path("2fa/disable/", TwoFactorDisableView.as_view(), name="two-factor-disable"),
    path(
        "role-permissions/",
        RolePermissionListView.as_view(),
        name="role-permission-list",
    ),
    path(
        "role-permissions/<str:role>/",
        RolePermissionReplaceView.as_view(),
        name="role-permission-replace",
    ),
    path("staff/", ManagedStaffListCreateView.as_view(), name="managed-staff-list"),
    path(
        "staff/<int:user_id>/role/",
        ManagedStaffRoleView.as_view(),
        name="managed-staff-role",
    ),
    path(
        "staff/<int:user_id>/status/",
        ManagedStaffStatusView.as_view(),
        name="managed-staff-status",
    ),
    path(
        "staff/<int:user_id>/resend-invitation/",
        ManagedStaffInvitationView.as_view(),
        name="managed-staff-resend-invitation",
    ),
    path(
        "staff/setup-password/",
        StaffPasswordSetupView.as_view(),
        name="staff-setup-password",
    ),
]
