import { fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import { beforeEach, describe, expect, test, vi } from "vitest";
import DeviceTelemetryReportPage from "./DeviceTelemetryReportPage";

const mocks = vi.hoisted(() => ({ fetchReport: vi.fn(), downloadCsv: vi.fn() }));
vi.mock("./api", () => ({ fetchDeviceTelemetryReport: mocks.fetchReport, downloadDeviceTelemetryCsv: mocks.downloadCsv }));
const device = { id: 1, device_id: "DEVICE-1", registration_status: "REGISTERED", registration_status_label: "Registered", registered_at: "2026-09-01T00:00:00Z", binding_state: "PAIRED", binding_state_label: "Paired", current_binding: { id: 1, paired_at: "2026-09-01T00:00:00Z", paired_by: "Fleet Manager", vehicle: { id: 1, name: "Report Van", identifier: "VEH-1" } }, latest_telemetry: { id: 2, recorded_at: "2026-09-20T04:00:00Z", received_at: "2026-09-20T04:00:01Z", position_source: "SIMULATED_TEST", position_source_label: "Simulated Test", position_accuracy_m: null, obd_source: "SIMULATED_TEST", obd_source_label: "Simulated Test", latitude: 14.51, longitude: 121.01 }, telemetry_state: "RECEIVED", telemetry_state_label: "Telemetry Received", binding_count: 2 };
const noTelemetry = { ...device, id: 2, device_id: "DEVICE-2", binding_state: "UNPAIRED", binding_state_label: "Unpaired", current_binding: null, latest_telemetry: null, telemetry_state: "NO_TELEMETRY", telemetry_state_label: "No Telemetry", binding_count: 0 };
const binding = { id: 1, device: { id: 1, device_id: "DEVICE-1", registration_status: "REGISTERED", registration_status_label: "Registered" }, vehicle: { id: 1, name: "Report Van", identifier: "VEH-1" }, paired_at: "2026-09-01T00:00:00Z", unpaired_at: null, binding_state: "ACTIVE", binding_state_label: "Active", paired_by: "Fleet Manager", unpaired_by: null };
const response = { meta: { title: "Device & Telemetry Availability", generated_at: "2026-09-21T00:00:00Z", generated_by: "Fleet Manager", timezone: "Asia/Manila", date_basis: "", date_from: "2026-08-23", date_to: "2026-09-21", telemetry_date_basis: "TelemetryEvent.recorded_at", binding_date_basis: "TelemetryDeviceBinding.paired_at", freshness_rule: null }, summary: { registered_devices: 97, paired_devices: 96, unpaired_devices: 1, retired_devices: 1, no_telemetry: 1 }, trend: [{ date: "2026-09-20", count: 120 }], breakdowns: { availability: [{ value: "RECEIVED", label: "Telemetry Received", count: 96 }, { value: "NO_TELEMETRY", label: "No Telemetry", count: 1 }], binding_state: [{ value: "PAIRED", label: "Paired", count: 96 }, { value: "UNPAIRED", label: "Unpaired", count: 1 }], position_sources: [{ value: "SIMULATED_TEST", label: "Simulated Test", count: 80 }], obd_sources: [{ value: "SIMULATED_TEST", label: "Simulated Test", count: 80 }, { value: "NO_OBD_DATA", label: "No OBD Data", count: 17 }] }, choices: { registry_statuses: [{ value: "REGISTERED", label: "Registered" }], vehicles: [{ value: 1, label: "Report Van · VEH-1" }], devices: [{ value: 1, label: "DEVICE-1" }], position_sources: [{ value: "SIMULATED_TEST", label: "Simulated Test" }], obd_sources: [{ value: "SIMULATED_TEST", label: "Simulated Test" }] }, devices: { count: 16, page: 1, page_size: 15, total_pages: 2, results: [device, noTelemetry] }, bindings: { count: 1, page: 1, page_size: 15, total_pages: 1, results: [binding] } };

beforeEach(() => { vi.clearAllMocks(); mocks.fetchReport.mockResolvedValue(response); mocks.downloadCsv.mockResolvedValue(undefined); });

describe("Device & Telemetry Availability", () => {
  test("renders current KPIs, truthful availability, and provenance", async () => { render(<MemoryRouter><DeviceTelemetryReportPage /></MemoryRouter>); expect(await screen.findByText("DEVICE-1")).toBeInTheDocument(); const summary = within(screen.getByLabelText("Report summary")); expect(summary.getByText("97")).toBeInTheDocument(); expect(screen.queryByText("Telemetry Event Volume")).not.toBeInTheDocument(); expect(screen.getAllByText("Simulated Test").length).toBeGreaterThan(0); expect(screen.getByText("No telemetry received")).toBeInTheDocument(); expect(screen.queryByText(/Online|Offline|Uptime|Device Health Score/)).not.toBeInTheDocument(); });
  test("filters and paginates devices, opens read-only drawer, and exports", async () => { render(<MemoryRouter><DeviceTelemetryReportPage /></MemoryRouter>); await screen.findByText("DEVICE-1"); fireEvent.change(screen.getByLabelText("Device search"), { target: { value: "DEVICE" } }); await waitFor(() => expect(mocks.fetchReport).toHaveBeenLastCalledWith(expect.objectContaining({ device_search: "DEVICE", device_page: 1 }))); fireEvent.click(screen.getByRole("button", { name: "Next" })); await waitFor(() => expect(mocks.fetchReport).toHaveBeenLastCalledWith(expect.objectContaining({ device_page: 2 }))); fireEvent.click(screen.getAllByRole("button", { name: "View" })[0]); expect(screen.getByLabelText("Device details")).toBeInTheDocument(); expect(screen.getByText("121.01")).toBeInTheDocument(); expect(screen.queryByRole("button", { name: /Pair|Unpair|Retire/ })).not.toBeInTheDocument(); fireEvent.click(screen.getByRole("button", { name: "Export Device Summary CSV" })); expect(mocks.downloadCsv).toHaveBeenCalledWith("devices", expect.any(Object)); });
  test("switches to binding history, filters, opens detail, and exports", async () => { render(<MemoryRouter><DeviceTelemetryReportPage /></MemoryRouter>); await screen.findByText("DEVICE-1"); fireEvent.click(screen.getByRole("button", { name: "Binding History" })); fireEvent.change(screen.getByLabelText("Binding search"), { target: { value: "VEH-1" } }); await waitFor(() => expect(mocks.fetchReport).toHaveBeenLastCalledWith(expect.objectContaining({ binding_search: "VEH-1", binding_page: 1 }))); fireEvent.click(screen.getByRole("button", { name: "View" })); expect(screen.getByLabelText("Binding details")).toBeInTheDocument(); expect(screen.getAllByText("Fleet Manager").length).toBeGreaterThan(0); fireEvent.click(screen.getByRole("button", { name: "Export Binding History CSV" })); expect(mocks.downloadCsv).toHaveBeenCalledWith("bindings", expect.any(Object)); });
  test("distinguishes empty data from API failure", async () => { mocks.fetchReport.mockResolvedValueOnce({ ...response, devices: { ...response.devices, count: 0, total_pages: 0, results: [] } }); const { unmount } = render(<MemoryRouter><DeviceTelemetryReportPage /></MemoryRouter>); expect(await screen.findByText("No devices match the current filters.")).toBeInTheDocument(); unmount(); mocks.fetchReport.mockRejectedValueOnce(new Error("offline")); render(<MemoryRouter><DeviceTelemetryReportPage /></MemoryRouter>); expect(await screen.findByText("Unable to load this report.")).toBeInTheDocument(); expect(screen.queryByLabelText("Report summary")).not.toBeInTheDocument(); });
});
