import { fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import { beforeEach, describe, expect, test, vi } from "vitest";
import FleetAssignmentReportPage from "./FleetAssignmentReportPage";

const mocks = vi.hoisted(() => ({ fetchReport: vi.fn(), downloadCsv: vi.fn() }));
vi.mock("./api", () => ({ fetchFleetAssignmentReport: mocks.fetchReport, downloadFleetAssignmentCsv: mocks.downloadCsv }));
const assignment = { id: 1, request_id: "request-1", request_number: "TR-001", vehicle: { id: 1, name: "Alpha Van", identifier: "VEH-1" }, driver: { id: 1, code: "DRV-1", name: "Maria Reyes" }, selection_mode_label: "Optimized", execution_status: "ASSIGNED", execution_status_label: "Assigned", confirmed_at: "2026-09-20T04:00:00Z" };
const vehicle = { id: 1, name: "Alpha Van", identifier: "VEH-1", plate_number: "ABC-1", vehicle_type: "VAN", vehicle_type_label: "Van", fuel_type: "GASOLINE", fuel_type_label: "Gasoline", fuel_grade: "UNLEADED_91", fuel_grade_label: "Unleaded 91", is_active: true, passenger_capacity: 8, payload_capacity_kg: null, assignments: 1, completed_trips: 0, current_assignment: assignment, latest_assignment: assignment };
const zeroDriver = { id: 2, name: "No Trips", driver_code: "DRV-2", employment_status: "ON_LEAVE", employment_status_label: "On leave", assignments: 0, completed_trips: 0, current_assignment: null, latest_assignment: null };
const response = { meta: { title: "Fleet Assignment Summary", generated_at: "2026-09-21T00:00:00Z", generated_by: "Fleet Manager", timezone: "Asia/Manila", date_basis: "DispatchAssignment.confirmed_at / completed_at", date_from: "2026-08-23", date_to: "2026-09-21" }, summary: { active_vehicles: 96, active_drivers: 30, assignments_confirmed: 1, completed_trips: 0, currently_assigned_vehicles: 1 }, trend: [{ date: "2026-09-20", count: 1 }], breakdowns: { by_vehicle: [{ value: 1, label: "Alpha Van · VEH-1", count: 1 }], by_driver: [{ value: 1, label: "DRV-1 · Maria Reyes", count: 1 }], by_vehicle_type: [{ value: "VAN", label: "Van", count: 1 }] }, choices: { vehicles: [{ value: 1, label: "Alpha Van · VEH-1" }], vehicle_types: [{ value: "VAN", label: "Van" }], drivers: [{ value: 1, label: "DRV-1 · Maria Reyes" }], employment_statuses: [{ value: "ACTIVE", label: "Active" }] }, vehicles: { count: 16, page: 1, page_size: 15, total_pages: 2, results: [vehicle] }, drivers: { count: 1, page: 1, page_size: 15, total_pages: 1, results: [zeroDriver] } };

beforeEach(() => { vi.clearAllMocks(); mocks.fetchReport.mockResolvedValue(response); mocks.downloadCsv.mockResolvedValue(undefined); });

describe("Fleet Assignment Summary", () => {
  test("renders truthful KPIs and vehicle fuel classification", async () => { render(<MemoryRouter><FleetAssignmentReportPage /></MemoryRouter>); expect(await screen.findByText("Alpha Van")).toBeInTheDocument(); const summary = within(screen.getByLabelText("Report summary")); expect(summary.getByText("96")).toBeInTheDocument(); expect(screen.getByText("Gasoline")).toBeInTheDocument(); expect(screen.getByText("Unleaded 91")).toBeInTheDocument(); expect(screen.queryByText(/Utilization %|Safety Score/i)).not.toBeInTheDocument(); });
  test("filters and independently paginates vehicles", async () => { render(<MemoryRouter><FleetAssignmentReportPage /></MemoryRouter>); await screen.findByText("Alpha Van"); fireEvent.change(screen.getByLabelText("Vehicle search"), { target: { value: "Alpha" } }); await waitFor(() => expect(mocks.fetchReport).toHaveBeenLastCalledWith(expect.objectContaining({ vehicle_search: "Alpha", vehicle_page: 1 }))); fireEvent.click(screen.getByRole("button", { name: "Next" })); await waitFor(() => expect(mocks.fetchReport).toHaveBeenLastCalledWith(expect.objectContaining({ vehicle_page: 2 }))); });
  test("switches to zero-count drivers, opens safe drawer, and exports selected tab", async () => { render(<MemoryRouter><FleetAssignmentReportPage /></MemoryRouter>); await screen.findByText("Alpha Van"); fireEvent.click(screen.getByRole("button", { name: "Drivers" })); expect(screen.getByText("No Trips")).toBeInTheDocument(); expect(screen.getAllByText("0").length).toBeGreaterThan(0); fireEvent.click(screen.getByRole("button", { name: "View" })); expect(screen.getByLabelText("Driver assignment details")).toBeInTheDocument(); expect(screen.queryByText(/email|phone|license/i)).not.toBeInTheDocument(); fireEvent.click(screen.getByRole("button", { name: "Export Driver CSV" })); expect(mocks.downloadCsv).toHaveBeenCalledWith("drivers", expect.any(Object)); });
  test("shows an error without plausible zero totals and retries", async () => { mocks.fetchReport.mockRejectedValueOnce(new Error("offline")).mockResolvedValueOnce(response); render(<MemoryRouter><FleetAssignmentReportPage /></MemoryRouter>); expect(await screen.findByText("Unable to load this report.")).toBeInTheDocument(); expect(screen.queryByLabelText("Report summary")).not.toBeInTheDocument(); fireEvent.click(screen.getByRole("button", { name: "Retry" })); expect(await screen.findByText("Alpha Van")).toBeInTheDocument(); });
});
