import { fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import { beforeEach, describe, expect, test, vi } from "vitest";
import SafetyGeofenceReportPage from "./SafetyGeofenceReportPage";

const mocks = vi.hoisted(() => ({ fetchReport: vi.fn(), downloadCsv: vi.fn() }));
vi.mock("./api", () => ({ fetchSafetyGeofenceReport: mocks.fetchReport, downloadSafetyGeofenceCsv: mocks.downloadCsv }));
const safety = { id: 1, event_id: "event-1", occurred_at: "2026-09-20T04:00:00Z", event_type: "HARSH_BRAKING", event_type_label: "Harsh Braking", driver: { id: 2, code: "DRV-1", name: "Maria Reyes" }, assignment: { id: 3, request_number: "TR-001" }, vehicle: { id: 1, name: "Safety Van", identifier: "SAFE-1" }, device_id: "DEVICE-1", position_source: "GNSS", position_source_label: "GNSS", obd_source: "PHYSICAL_OBD", obd_source_label: "Physical OBD", provenance: "OPERATIONAL" };
const restricted = { id: 2, occurred_at: "2026-09-20T05:00:00Z", created_at: "2026-09-20T05:00:01Z", event_type: "ENTER", event_type_label: "Entered", display_classification: "Restricted Zone Entry", geofence: { id: "geo-1", name: "Restricted Yard", category: "RESTRICTED", category_label: "Restricted area", shape_type: "CIRCLE", shape_type_label: "Circle", radius_meters: 100 }, vehicle: { id: 1, name: "Safety Van", identifier: "SAFE-1" }, latitude: 14.51, longitude: 121.01, telemetry: { id: 1, event_id: "event-1", recorded_at: "2026-09-20T04:00:00Z", position_source: "SIMULATED_TEST", position_source_label: "Simulated Test", obd_source: "SIMULATED_TEST", obd_source_label: "Simulated Test" } };
const sos = { id: 4, status: "ACTIVE", status_label: "Active", source: "PHYSICAL_BUTTON", source_label: "Physical emergency button", activated_at: "2026-09-20T06:00:00Z", cleared_at: null, device: { id: 1, device_id: "DEVICE-1" }, vehicle: { id: 1, name: "Safety Van", identifier: "SAFE-1" }, driver: { id: 2, code: "DRV-1", name: "Maria Reyes" }, location: null, location_label: "Location not stored" };
const response = { meta: { title: "Safety, Geofence & SOS Activity", generated_at: "2026-09-21T00:00:00Z", generated_by: "Fleet Manager", timezone: "Asia/Manila", date_basis: "", date_from: "2026-08-23", date_to: "2026-09-21", safety_date_basis: "DriverSafetyEvent.occurred_at", geofence_date_basis: "GeofenceEvent.occurred_at", sos_date_basis: "VehicleEmergencySOS.activated_at" }, summary: { safety_events: 1, harsh_braking: 1, harsh_acceleration: 0, sharp_turns: 0, restricted_entries: 1, geofence_activity: 1, sos_activations: 1, active_sos: 1 }, safety_trend: [{ date: "2026-09-20", count: 1 }], geofence_trend: [{ date: "2026-09-20", enter: 1, exit: 0, count: 1 }], breakdowns: { safety_types: [{ value: "HARSH_BRAKING", label: "Harsh Braking", count: 1 }, { value: "HARSH_ACCELERATION", label: "Harsh Acceleration", count: 0 }, { value: "SHARP_TURN", label: "Sharp Turn", count: 0 }], position_sources: [{ value: "GNSS", label: "GNSS", count: 1 }], geofence_events: [{ value: "ENTER", label: "Entered", count: 1 }, { value: "EXIT", label: "Exited", count: 0 }], restricted_by_geofence: [{ value: "geo-1", label: "Restricted Yard", count: 1 }] }, choices: { safety_event_types: [{ value: "HARSH_BRAKING", label: "Harsh Braking" }], vehicles: [{ value: 1, label: "Safety Van · SAFE-1" }], drivers: [{ value: 2, label: "DRV-1 · Maria Reyes" }], position_sources: [{ value: "GNSS", label: "GNSS" }], obd_sources: [{ value: "PHYSICAL_OBD", label: "Physical OBD" }], geofence_event_types: [{ value: "ENTER", label: "Entered" }], categories: [{ value: "RESTRICTED", label: "Restricted area" }], geofences: [{ value: "geo-1", label: "Restricted Yard" }], sos_statuses: [{ value: "ACTIVE", label: "Active" }] }, safety_events: { count: 16, page: 1, page_size: 15, total_pages: 2, results: [safety] }, geofence_activity: { count: 1, page: 1, page_size: 15, total_pages: 1, results: [restricted] }, sos_activity: { count: 1, page: 1, page_size: 15, total_pages: 1, results: [sos] } };

beforeEach(() => { vi.clearAllMocks(); mocks.fetchReport.mockResolvedValue(response); mocks.downloadCsv.mockResolvedValue(undefined); });

describe("Safety & Geofence Activity", () => {
  test("renders operational safety attribution and factual KPIs", async () => { render(<MemoryRouter><SafetyGeofenceReportPage /></MemoryRouter>); expect(await screen.findByText("Safety Van")).toBeInTheDocument(); const summary = within(screen.getByLabelText("Report summary")); expect(summary.getByText("Safety Events")).toBeInTheDocument(); expect(screen.queryByText("Safety Events Over Time")).not.toBeInTheDocument(); expect(screen.getByText("Maria Reyes")).toBeInTheDocument(); expect(screen.getByText(/TR-001/)).toBeInTheDocument(); expect(screen.queryByText(/Driver Safety Score/)).not.toBeInTheDocument(); });
  test("applies safety filters, paginates, opens attribution drawer, and exports", async () => { render(<MemoryRouter><SafetyGeofenceReportPage /></MemoryRouter>); await screen.findByText("Safety Van"); fireEvent.change(screen.getByLabelText("Safety search"), { target: { value: "DRV-1" } }); await waitFor(() => expect(mocks.fetchReport).toHaveBeenLastCalledWith(expect.objectContaining({ safety_search: "DRV-1", safety_page: 1 }))); fireEvent.click(screen.getByRole("button", { name: "Next" })); await waitFor(() => expect(mocks.fetchReport).toHaveBeenLastCalledWith(expect.objectContaining({ safety_page: 2 }))); fireEvent.click(screen.getByRole("button", { name: "View" })); expect(screen.getByLabelText("Safety event details")).toBeInTheDocument(); expect(screen.getByText("event-1")).toBeInTheDocument(); fireEvent.click(screen.getByRole("button", { name: "Close details" })); fireEvent.click(screen.getByRole("button", { name: "Export Safety Events CSV" })); expect(mocks.downloadCsv).toHaveBeenCalledWith("safety", expect.any(Object)); });
  test("shows SOS without invented location and exports it", async () => { render(<MemoryRouter><SafetyGeofenceReportPage /></MemoryRouter>); await screen.findByText("Safety Van"); fireEvent.click(screen.getByRole("button", { name: "SOS Activity" })); expect(screen.getByText("Location not stored")).toBeInTheDocument(); fireEvent.click(screen.getByRole("button", { name: "View" })); expect(screen.getByLabelText("SOS activity details")).toBeInTheDocument(); fireEvent.click(screen.getByRole("button", { name: "Export SOS Activity CSV" })); expect(mocks.downloadCsv).toHaveBeenCalledWith("sos", expect.any(Object)); });
  test("switches to geofences, derives restricted entry, filters, opens drawer, and exports", async () => { render(<MemoryRouter><SafetyGeofenceReportPage /></MemoryRouter>); await screen.findByText("Safety Van"); fireEvent.click(screen.getByRole("button", { name: "Geofence Activity" })); expect(screen.getAllByText("Restricted Zone Entry").length).toBeGreaterThan(0); fireEvent.change(screen.getByLabelText("Geofence search"), { target: { value: "Yard" } }); await waitFor(() => expect(mocks.fetchReport).toHaveBeenLastCalledWith(expect.objectContaining({ geofence_search: "Yard", geofence_page: 1 }))); fireEvent.click(screen.getByRole("button", { name: "View" })); expect(screen.getByLabelText("Geofence activity details")).toBeInTheDocument(); expect(screen.getByText("Circle")).toBeInTheDocument(); fireEvent.click(screen.getByRole("button", { name: "Export Geofence Activity CSV" })); expect(mocks.downloadCsv).toHaveBeenCalledWith("geofence", expect.any(Object)); });
  test("renders a successful empty state and distinguishes API failure", async () => { mocks.fetchReport.mockResolvedValueOnce({ ...response, summary: { ...response.summary, safety_events: 0 }, safety_trend: [], safety_events: { ...response.safety_events, count: 0, total_pages: 0, results: [] } }); const { unmount } = render(<MemoryRouter><SafetyGeofenceReportPage /></MemoryRouter>); expect((await screen.findAllByText(/No (operational )?safety events match/)).length).toBeGreaterThan(0); unmount(); mocks.fetchReport.mockRejectedValueOnce(new Error("offline")); render(<MemoryRouter><SafetyGeofenceReportPage /></MemoryRouter>); expect(await screen.findByText("Unable to load this report.")).toBeInTheDocument(); expect(screen.queryByLabelText("Report summary")).not.toBeInTheDocument(); });
});
